spring:
  application:
    name: mailservice

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: ${PORT:${SERVER_PORT:8081}}