INSERT INTO categories (name, description) VALUES
('Alimentos e Bebidas', 'Comidas, bebidas, ingredientes e refeições'),
('Objetos Domésticos', 'Objetos utilizados dentro de casa'),
('Tecnologia', 'Computadores, celulares, softwares e dispositivos eletrônicos'),
('Escritório e Trabalho', 'Objetos e termos relacionados ao ambiente profissional'),
('Educação e Estudos', 'Materiais escolares, ensino e aprendizagem'),
('Animais', 'Animais domésticos, rurais e selvagens'),
('Veículos e Transporte', 'Meios de transporte terrestres, marítimos e aéreos'),
('Corpo Humano', 'Partes do corpo, órgãos e características físicas'),
('Saúde e Medicina', 'Equipamentos médicos, medicamentos e instrumentos de saúde'),
('Roupas e Acessórios', 'Vestuário, calçados e acessórios pessoais'),
('Casa e Construção', 'Estruturas, cômodos, móveis e materiais de construção'),
('Natureza e Meio Ambiente', 'Plantas, flores, árvores e elementos naturais'),
('Esportes e Exercícios', 'Equipamentos esportivos, bolas e acessórios físicos'),
('Lazer e Entretenimento', 'Jogos, hobbies, instrumentos musicais e objetos de diversão'),
('Viagens e Turismo', 'Objetos de viagem, mochilas, passaportes e equipamentos'),
('Compras e Comércio', 'Produtos, sacolas, embalagens e artigos de loja'),
('Comunicação', 'Celulares, computadores, telefones e dispositivos de comunicação'),
('Arte e Cultura', 'Pinturas, esculturas, livros, instrumentos e objetos culturais'),
('Jogos e Videogames', 'Consoles, controles, jogos e acessórios gamers'),
('Culinária', 'Utensílios culinários, panelas, talheres e utensílios'),
('Ferramentas e Equipamentos', 'Ferramentas manuais, industriais e equipamentos'),
('Outras', 'Palavras que não se encaixam nas demais categorias');