INSERT INTO categories (name, description) VALUES
('Alimentos e Bebidas', 'Comidas, bebidas, ingredientes e refeições'),
('Objetos Domésticos', 'Objetos utilizados dentro de casa'),
('Tecnologia', 'Computadores, celulares, softwares e dispositivos eletrônicos'),
('Escritório e Trabalho', 'Objetos e termos relacionados ao ambiente profissional'),
('Educação e Estudos', 'Materiais escolares, ensino e aprendizagem'),
('Animais', 'Animais domésticos, rurais e selvagens'),
('Veículos e Transporte', 'Meios de transporte terrestres, marítimos e aéreos'),
('Corpo Humano', 'Partes do corpo, órgãos e características físicas'),
('Saúde e Medicina', 'Doenças, tratamentos, medicamentos e cuidados médicos'),
('Roupas e Acessórios', 'Vestuário, calçados e acessórios pessoais'),
('Casa e Construção', 'Estruturas, cômodos, móveis e materiais de construção'),
('Natureza e Meio Ambiente', 'Plantas, clima, fenômenos naturais e ecossistemas'),
('Profissões', 'Cargos, carreiras e atividades profissionais'),
('Esportes e Exercícios', 'Modalidades esportivas e atividades físicas'),
('Lazer e Entretenimento', 'Jogos, hobbies, cinema, música e diversão'),
('Viagens e Turismo', 'Locais, hospedagem, aeroportos e turismo'),
('Compras e Comércio', 'Lojas, vendas, produtos e serviços'),
('Finanças e Economia', 'Dinheiro, bancos, investimentos e negócios'),
('Comunicação', 'Idiomas, conversação, escrita e meios de comunicação'),
('Família e Relacionamentos', 'Parentesco, amizades e relações sociais'),
('Emoções e Sentimentos', 'Estados emocionais e psicológicos'),
('Tempo e Calendário', 'Datas, horários, estações e períodos'),
('Geografia e Lugares', 'Países, cidades, regiões e pontos de referência'),
('Arte e Cultura', 'Pintura, literatura, teatro e manifestações culturais'),
('Ciência e Tecnologia', 'Conceitos científicos e tecnológicos'),
('Internet e Redes Sociais', 'Sites, aplicativos e plataformas digitais'),
('Jogos e Videogames', 'Games, consoles e universo gamer'),
('Culinária', 'Preparação de alimentos e técnicas culinárias'),
('Ferramentas e Equipamentos', 'Ferramentas manuais, industriais e equipamentos'),
('Outras', 'Palavras que não se encaixam nas demais categorias');